# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.org.nz.fhir.ig.formulary
canonical: https://fhir-docs.nzf.org.nz
name: NZFormulary IG
title: HL7 FHIR Implementation Guide - New Zealand Formulary/NZULM IG
description: IG that details how to use the New Zealand Formulary/NZULM FHIR server
publisher:
  name: New Zealand Medicines Formulary LP
  email: mailto:fhir@nzformulary.org
status: active
version: 1.0.0
fhirVersion: 4.3.0
copyrightYear: 2021+
releaseLabel: ci-build


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  How to use: howtouse.html
  Data: data.html
  Glossary: glossary.html
  FAQ: faq.html
  Roadmap: roadmap.html
  Change log: changelog.html
  Extensions: extensions.html
  Profiles: profiles.html
  Artifacts: artifacts.html
