# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.nzformulary
canonical: http://example.org
name: NZFormulary IG
title: HL7 FHIR Implementation Guide - New Zealand Formulary/NZULM IG
description: IG that details how to use the New Zealand Formulary/NZULM FHIR server
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: New Zealand Medicines Formulary LP
  url: http://nzformulary.org/

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Mappings: mapping.html
  Use cases: use-cases.html
  Roadmap: roadmap.html
  FAQ: faq.html
