# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.org.nz.fhir.ig.formulary
canonical: http://hl7.org.nz/fhir/ig/formulary
name: NZFormulary IG
title: HL7 FHIR Implementation Guide - New Zealand Formulary/NZULM IG
description: IG that details how to use the New Zealand Formulary/NZULM FHIR server
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher: New Zealand Medicines Formulary LP

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Extensions: extensions.html
  Profiles: profiles.html
  Artifacts: artifacts.html
  Notes: notes.html
  Mappings: mapping.html
  Example queries: example-queries.html
  FAQ: faq.html
  Roadmap: roadmap.html
  Change log: changelog.html
